language: java
jdk: oraclejdk8

install: true
script: mvn install

cache:
  directories:
  - $HOME/.m2
  
after_success:
- pwd
- mkdir $HOME/buildApk/
- ls -l
- cd $HOME/buildApk/
- pwd
- ls -l
- git config --global user.email "loay.saada@gmail.com"
- git config --global user.name "Altayeb Saadeh"
- git clone --depth=50 --branch=master https://github.com/altayeb1980/HotelDeals.git
- cd HotelDeals
- ls -l
- cp -r /home/travis/build/altayeb1980/HotelDeals/target $HOME/buildApk/HotelDeals
- ls -l
- git add .
- git remote rm origin
- git remote add origin https://$GITHUB_TOKEN@github.com/altayeb1980/HotelDeals.git
- git add .
- git commit -m "Travis Build $TRAVIS_BUILD_NUMBER pushed"
- git push -fq origin master
 