spring.profiles.active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/personality_test
    username: root
    password: ""
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id.new_generator_mappings: false
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
    
endpoints.sensitive: false