spring.profiles.active: production

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://${production_datasource_url}:3306/personality_test
    username: ${production_datasource_username}
    password: ${production_datasource_password}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id.new_generator_mappings: false
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
    
endpoints.sensitive: false