---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/personality_test_db
    username: root
    password: ""
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id.new_generator_mappings: false
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
    
endpoints.sensitive: false

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:2012/spring_app_db
    username: app_user
    password: test123
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id.new_generator_mappings: false
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
    
endpoints.sensitive: false

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQ
    show-sql: false
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id.new_generator_mappings: false

endpoints.sensitive: false